### ISSUE TITLE
Is it possible to show exif info?

### ISSUE THREAD

**Issue by dofine** [chaosarium/arxive#3]
Thank you so much for this theme. But is it possible to add support for exif info?

**Comment by chaosarium** [comment]
The theme currently doesn't show exif info.

It should be possible as thumbsup's data model includes exif info under metadata (see https://thumbsup.github.io/docs/4-themes/data-model/).

By default, thumbsup disables exif metadata when building the site. There is a `--embed-exif` flag to enable it (see https://thumbsup.github.io/docs/3-configuration/cheat-sheet/). This should add exif metadata as html attributes (for reference, link to [tumbnail.hbs](https://github.com/chaosarium/PhotoArchive/blob/master/partials/thumbnail.hbs)). Not sure if this is what you want.

**Comment by chaosarium** [comment]
Also, data in the `data-sub-html` field gets displayed when viewing individual images, so one might be able to add relevant exif info there.

**Comment by dofine** [comment]
Thank you for the guidance. 
I find the exif info already in the html source, now I'll try to give it a nice frontend view.
